<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //에러발생시 아래 내용이 실행이 안됨으로 예외처리 해야함 
        //=> 에러가 나더라도 밑에 내용이 실행
        try {
            //오류가 날수 있는 구문
            console.log('AAAA');
            const result = new Array(-1);
            console.log('BBBB');
        } catch(e) {
            //에러발생시에 보여지는 내용 작성해주면 된다
            console.log(e); //에러객체 확인
            console.log(e.name); //에러객체의 네이밍 확인
            console.error('catch : ' + e.name);
        }
        
        console.log('(1) try_catch 끝');

        console.log('-----------------');
        try {
            //오류가 날수 있는 구문
            console.log('AAAA');
            console.log('BBBB');
            console.log('CCCC');
        } catch(e) {
            //에러발생시에 보여지는 내용(무조건 실행 X)
            console.log(e); //에러객체 확인
            console.error(e.name); //에러객체의 네이밍 확인
        }

        console.log('(2) try_catch 끝');

        console.log('-----------------');

        try {
            //오류가 날수 있는 구문
            console.log('AAAA');
            const result = new Array(-1);
            console.log('BBBB');
        } catch(e) {
            console.error('catch : ' + e.name);
        } finally {
            //예외 여부 상관 없이 무조건 실행
            //함수에서 사용할 시에 finally 안에 내용적는 것과 밖에 적는게 차이난다!!
            console.log('무조건 실행 됨!');
        }

        console.log('(3) try_catch 끝');

        console.log('-----------------');
    </script>
</body>
</html>